# Generated by Django 4.1.3 on 2022-12-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
