# Generated by Django 4.1.3 on 2022-12-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_hotels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotels',
        ),
    ]
